<?php
use app\helpers\UtilityHelper;
$this->params['data'] = ['page' => 'terms', 'title' => 'Terms &amp; Conditions'];
?>
<section class="terms pmx-content">
  <div class="container">
    <h1 class="text-center">TERMS &amp; CONDITIONS</h1>

    <h2>Use of Website</h2>
    <p>Welcome to <?= UtilityHelper::getCustomParameters('SiteUrl'); ?>. Our website provides information on our products and services. By accessing or using our website, you are acknowledging that you have read, understand and agree to these Terms and Conditions. If you do not agree with any of these Terms and Conditions, do not use the <?= UtilityHelper::getCustomParameters('SiteUrl'); ?> website. If you proceed in use of our website, you agree, without limitation or qualification, to be bound by these Terms and Conditions. We reserve the right to change these Terms and Conditions at any time or date without notice. By accessing this website, contacting us, and by placing an order on <?= UtilityHelper::getCustomParameters('SiteUrl'); ?>, you agree to the terms and conditions set forth as below. Please read through these terms carefully before placing your order. Please also read our Privacy Policy regarding personal information provided by you, which is incorporated herein by reference. But in the event that important changes are made that we feel customers would like to know about, a notice of change may be sent or uploaded to the website to make this known.</p>
    <p class="mb-5">We encourage you to review and read these Terms and Conditions whenever you use our website, <a href="mailto:<?= UtilityHelper::getCustomParameters('SiteEmail'); ?>">contact us</a>, and place orders in case of any changes.</p>
    
    <h2>Intellectual Property</h2>
    <p>All content available on this website, including, but not limited to, text, graphics, logos, button icons, images, audio clips, video clips, data compilations and software, and the compilation thereof (the “Content”) is the property of <?= UtilityHelper::getCustomParameters('SiteName'); ?>. The Content is protected by United States and international copyright laws. The trademarks, logos and service marks displayed on this website (the “Trademarks”) are the registered and unregistered marks of <?= UtilityHelper::getCustomParameters('SiteName'); ?>, our affiliates, our licensors or our partners, in the United States and other countries, and are protected by United States and international trademark laws. All other trademarks not owned by us, our affiliates, our partners or our licensors that appear on the website are the property of their respective owners, who may or may not be affiliated with, connected to or sponsored by us. You may not use <?= UtilityHelper::getCustomParameters('SiteName'); ?>’s or its partners’ or affiliates’ trademarks and trade dress in connection with any product or service without the express permission of <?= UtilityHelper::getCustomParameters('SiteName'); ?>.</p>
    <p>You may not without the prior written permission of <?= UtilityHelper::getCustomParameters('SiteName'); ?> use any computer code, data mining software, “robot,” “bot,” “spider,” “scraper” or other automatic device, or program, algorithm or methodology having similar processes or functionality, or any manual process, to monitor or copy any of the Web pages, data or content found on this site or accessed through this site. You also may not engage in the mass downloading of files from this site, use the computer processing power of this site for purposes other than those permitted above, or flood this site with electronic traffic designed to slow or stop its operation.</p>
    <p class="mb-5">Please consult our Digital Millennium Copyright Act (DMCA) policy (https://www.<?= UtilityHelper::getCustomParameters('SiteUrl'); ?>/dmca) if you find or believe any information, content, or images on our website infringes your copyrights.</p>

    <h2>Orders</h2>
    <p>When you place an order, we will request certain details so that we may process your order quickly and efficiently. In addition to your name, address, email address, and phone number, we will also need your payment information, such as a credit card or debit card number.</p>
    <p>The only required information to place an order is your name, address, email address, phone number, and payment information. All information that is provided is the sole ownership of <?= UtilityHelper::getCustomParameters('SiteName'); ?> and will not be sold or distributed.</p>
    <p>We reserve the right, at our sole discretion, to refuse or cancel any order for any reason.</p>
    <p><?= UtilityHelper::getCustomParameters('SiteName'); ?> reserves the right, at our sole discretion, to limit the quantity of items purchased per person, per household or per order. These restrictions may be applicable to orders placed by the same account or the same credit card, and also to orders that use the same billing and/or shipping address. We will provide notification to the customer should such limits be applied.</p>
    <p>Some situations that may result in your order being cancelled include limitations on quantities available for purchase, inaccuracies or errors in product or pricing information or problems identified by our credit and fraud avoidance department. We may also require additional verifications or information before accepting any order. We will contact you if all or any portion of your order is cancelled or if additional information is required to accept your order. If your order is cancelled after your credit card has been charged, we will issue a credit to your credit card in the amount of the charge.</p>
    <p class="mb-5">Please also review our <a href="/returnpolicy">‘Return Policy and Refunds’</a> policies below before you place an order.</p>

    <h2>Subscription Terms and Conditions:</h2>
    <p class="mb-5">For your convenience and to maximize your results you will be enrolled in our auto ship program and in 21 days of placing your order we will automatically send you a fresh one-month supply of <?= UtilityHelper::getCustomParameters('SiteName'); ?> beginning in 28 days and every one-month thereafter for just $19.95 (free shipping), charged to the card you provide today. You may cancel anytime by emailing <a href="mailto:<?= UtilityHelper::getCustomParameters('SiteEmail'); ?>"><?= UtilityHelper::getCustomParameters('SiteEmail'); ?></a> or calling <a href="tel:<?= UtilityHelper::getCustomParameters('SitePhone'); ?>"><?= UtilityHelper::getCustomParameters('SitePhone'); ?></a>. No future commitments, no hassles. Cancel any time.</p>
    
    <h2>SMS Terms and Conditions</h2>
    <p class="mb-5">Subscription Service available on most carriers including U.S. Cellular, AT&T, Cellular One, T-Mobile, Sprint, Boost, MetroPCS, Verizon Wireless, Alltel Wireless and Virgin Mobile. Msg&Data Rates May Apply. Requires text-enabled handset. You may cancel your subscription by texting STOP to 79797. You can also get info directly on your phone by texting HELP to 79797 or contacting us at <a href="mailto:<?= UtilityHelper::getCustomParameters('SiteEmail'); ?>"><?= UtilityHelper::getCustomParameters('SiteEmail'); ?></a>. Service will continue until customer cancels. Carriers are not responsible for delayed or undelivered messages.</p>

    <h2>Shipping Terms</h2>
    <p class="mb-5">By placing an order with <?= UtilityHelper::getCustomParameters('SiteUrl'); ?>, you agree to our full Terms and Conditions. Orders are generally shipped within 1 business day (Monday through Friday excluding Federal Holidays) using United States Postal Service Priority Mail. Please be advised that shipments are not mailed out on Weekends or Federal Holidays. <?= UtilityHelper::getCustomParameters('SiteName'); ?> does not guarantee specific arrival dates or times and only provides estimates based on the information provided by the United States Postal Service. For more information please read the full Terms and Conditions page.</p>

    <h2>Customer Service</h2>
    <p>The information you provide to <?= UtilityHelper::getCustomParameters('SiteName'); ?> will be used to send you order, shipping confirmation responses, as well as Follow-up Telephone Calls and Emails. Customer service inquiries will be responded to via email or telephone, and you may specify your preferred method by advising us on through the following channels:</p>
    <p class="mb-0">Contact Us webpage: <a href="https://www.<?= UtilityHelper::getCustomParameters('SiteUrl'); ?>">https://www.<?= UtilityHelper::getCustomParameters('SiteUrl'); ?></a></p>
    <p>Email: <a href="mailto:<?= UtilityHelper::getCustomParameters('SiteEmail'); ?>"><?= UtilityHelper::getCustomParameters('SiteEmail'); ?></a></p>
    <p class="mb-5">Business Hours: Monday - Friday, 7AM – 1AM and Saturday – Sunday 8AM – 9PM (EST)</p>

    <h2>Special Offers</h2>
    <p>In addition to our Follow-up Telephone Calls and Emails, <?= UtilityHelper::getCustomParameters('SiteName'); ?> periodically offers special deals or discounts, which may be delivered by email or by physical mail. We may also contact you by telephone and/or email regarding these special offers and to hear feedback on our products. We respect your privacy, if you are not interested in receiving special offers you may opt out by advising us in :</p>
    <p>Our Contact Us webpage (<a href="https://www.<?= UtilityHelper::getCustomParameters('SiteUrl'); ?>">https://www.<?= UtilityHelper::getCustomParameters('SiteUrl'); ?></a>)</p>
    <p>Email <a href="mailto:<?= UtilityHelper::getCustomParameters('SiteEmail'); ?>"><?= UtilityHelper::getCustomParameters('SiteEmail'); ?></a></p>
    <p>During normal business hours: Monday - Friday, 7AM – 1AM and Saturday – Sunday 8AM – 9PM (EST). See ‘Opt Out’ section</p>
    <p class="mb-5"><a href="#">Unsubscribe from Email</a></p>

    <h2>Testimonials</h2>
    <p class="mb-5">Customer testimonials posted to this website have been done so with prior consent from real customers and have only been edited to adhere to proper grammatical and spelling standards to ensure readability. They are uploaded to provide real feedback to future and current customers. We disclose if a testimonial was provided in response to a free product or sample received.</p>

    <h2>Opt-Out</h2>
    <p>We respect your privacy, if you are not interested in receiving telephone calls, emails, physical mail, or newsletters from us, please advise us thru email at <?= UtilityHelper::getCustomParameters('SiteEmail'); ?> during normal business hours: Monday - Friday, 7AM – 1AM and Saturday – Sunday 8AM – 9PM (EST). This gives you the opportunity to opt-out of receiving telephone calls, emails, physical mail, or newsletters. For instance, if you have purchased a product and do not wish to receive any future correspondence regarding discounts, specials, or marketing materials, please advise us that you would like to opt-out of our database. In addition, if you feel you would like to receive promotional material or marketing material after already opting out, just reach out to us and we will do so accordingly.</p>
    <p class="mb-5">In addition, if you feel you would like to receive promotional material or marketing material after already opting out, you may advise us thru email at <?= UtilityHelper::getCustomParameters('SiteEmail'); ?> during normal business hours: Monday - Friday, 7AM – 1AM and Saturday – Sunday 8AM – 9PM (EST) and indicate that you would like to do so.</p>

    <h2>Return Policy & Refunds</h2>
    <p>If you are not 100% satisfied with your purchase, you can return the product for a full refund, less the cost of shipping. You can return a product for up to 30 days from date of purchase. We must receive your return within the 30 - day grace period in order to complete your return successfully. Simply contact Customer Care to initiate the return process and receive a valid Return Merchandise</p>
    <p class="mb-5">Authorization Number. You may send the unopened or remaining product to the address we provide. You are only responsible for the cost of return shipping. It generally takes 2-10 business days to process your refund.</p>

    <h2>Accuracy of Information and Colors</h2>
    <p class="mb-5">We attempt to be as accurate as possible when describing our products, pricing and availability on this website. However, to the extent permitted by applicable law, we do not warrant that the product descriptions, colors or other content available on the website is 100% accurate, complete, reliable, current or error-free.</p>

    <h2>Pricing</h2>
    <p>PRICES AND AVAILABILITY OF THE PRODUCTS AND SERVICES LISTED ON THE SITE ARE SUBJECT TO CHANGE WITHOUT NOTICE. The prices displayed on this website are quoted in U.S. dollars and are valid and effective only in the United States.</p>
    <p class="mb-5">While <?= UtilityHelper::getCustomParameters('SiteName'); ?> strives to provide accurate product and pricing information, pricing or typographical errors may occur. In the event a product or service is listed at an incorrect price due to a typographical error, or any other reason, we shall have the right to refuse or cancel any order placed for such product or service at the incorrect price, even if the order has been confirmed and/or your credit card has been charged. In the event that an item is mispriced, <?= UtilityHelper::getCustomParameters('SiteName'); ?> may, at our discretion, either contact you for instructions or cancel your order and notify you of such cancellation. If your credit card has already been charged for the purchase and your order is cancelled, we shall promptly issue a credit to your credit card account in the amount of the incorrect price.</p>

    <h2>Log Files</h2>
    <p>As with most websites you visit, certain files are collected and stored digitally when you enter or leave. This information does not pertain to an individual’s identity. What is saved is an Internet Protocol (IP) address, operating system, time on site, click patterns, navigation patterns, age of people who are on the website, and demographics, as well as buying habits based on this data. This information is used to analyze web traffic and for third-party advertisers.</p>
    <p>In addition, cookies are also collected. This is a small text file that is stored for record-keeping purposes, and to make your experience more enjoyable. For instance, cookies will allow you to save shipping or payment information, so it does not have to be reentered multiple times. This website is still fully functional even if cookies are disabled. This statement covers</p>
    <p class="mb-5"><?= UtilityHelper::getCustomParameters('SiteName'); ?> and its parent companies and does not apply to third-party advertisers or companies.</p>

    <h2>Legal Disclaimer</h2>
    <p>OUR WEBSITE IS PRESENTED “AS IS.” <?= UtilityHelper::getCustomParameters('SiteName'); ?> MAKES NO REPRESENTATIONS OR WARRANTIES OF ANY KIND WHATSOEVER, EXPRESS OR IMPLIED, IN CONNECTION WITH THESE TERMS AND CONDITIONS OR THE WEBSITE, INCLUDING, BUT NOT LIMITED TO, WARRANTIES OF MERCHANTABILITY, NON-INFRINGEMENT, OR FITNESS FOR A PARTICULAR PURPOSE, UNLESS SUCH REPRESENTATIONS AND WARRANTIES ARE NOT LEGALLY EXCLUDABLE. YOU AGREE THAT <?= UtilityHelper::getCustomParameters('SiteName'); ?> WILL NOT BE RESPONSIBLE OR LIABLE, UNDER ANY CIRCUMSTANCES, FOR ANY (a) INTERRUPTION OF BUSINESS;</p>
    <p>(b) ACCESS DELAYS OR ACCESS INTERRUPTIONS TO THE WEBSITE; (c) DATA NON-DELIVERY, MISDELIVERY, CORRUPTION, DESTRUCTION OR OTHER MODIFICATION; (d) LOSS OR DAMAGES OF ANY SORT INCURRED AS A RESULT OF DEALINGS WITH OR THE PRESENCE OF OFF-WEBSITE LINKS ON THE WEBSITE;</p>
    <p>(e) COMPUTER VIRUSES, SYSTEM FAILURE OR MALFUNCTION WHICH MAY OCCUR IN CONNECTION WITH YOUR USE OF THE WEBSITE, INCLUDING DURING HYPERLINK TO OR FROM THIRD-PARTY WEBSITES; OR</p>
    <p>(f) EVENTS BEYOND OUR REASONABLE CONTROL. FURTHER, TO THE MAXIMUM EXTENT PERMITTED BY LAW, WE WILL NOT BE LIABLE FOR ANY INDIRECT, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES OF ANY KIND (INCLUDING LOST PROFITS) RELATED TO THE WEBSITE REGARDLESS OF THE FORM OF ACTION WHETHER IN CONTRACT, TORT (INCLUDING NEGLIGENCE) OR OTHERWISE, EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. IN NO EVENT SHALL OUR MAXIMUM AGGREGATE LIABILITY EXCEED ONE HUNDRED DOLLARS ($100.00).</p>
    <p><?= UtilityHelper::getCustomParameters('SiteName'); ?> MAKES NO REPRESENTATION THAT CONTENT PROVIDED ON THIS WEBSITE IS APPLICABLE OR APPROPRIATE FOR USE IN LOCATIONS OUTSIDE OF THE UNITED STATES.</p>
    <p><?= UtilityHelper::getCustomParameters('SiteName'); ?> ASSUMES NO RISK OR RESPONSIBILITY FOR YOUR USE OF ANY OF THE CONTENT PROVIDED ON THIS WEBSITE.</p>
    <p>THE INFORMATION CONTAINED ON THIS WEBSITE REFERENCING INGREDIENTS, PROCESSES, MEDICINES AND TREATMENTS ARE INTENDED AS AN EDUCATIONAL AID ONLY. IT IS NOT INTENDED AS MEDICAL ADVICE FOR INDIVIDUAL CONDITIONS OR TREATMENT. IT IS NOT A SUBSTITUTE FOR MEDICAL ADVICE, NOR DOES IT REPLACE THE NEED FOR SERVICES PROVIDED BY MEDICAL PROFESSIONALS. <?= UtilityHelper::getCustomParameters('SiteName'); ?> RECOMMENDS SPEAKING WITH YOUR DOCTOR OR PHARMACIST BEFORE CHANGING YOUR PERSONAL CARE REGIMEN OR TAKING ANY DIETARY SUPPLEMENT, DRUGS, OR MEDICINES. ONLY YOUR DOCTOR OR PHARMACIST CAN PROVIDE YOU WITH ADVICE ON WHAT IS SAFE AND EFFECTIVE FOR YOU.</p>
    <p class="mb-5">We will comply with all law enforcement, courts, and other judicial systems in accordance with the law, and we reserve the right to disclose any private details to comply with the aforementioned parties.</p>

    <h2>Security</h2>
    <p>The safety of your personal information is paramount to us. When your orders are processed, and payment information is sent, it is encrypted with secure socket layer technology (SSL) to ensure that it is not hacked or intercepted by malicious parties. All of your credit card information is encrypted and stored in cold storage (offline).</p>
    <p class="mb-5">Please also review our Privacy Policy for how your account information is used.</p>

    <h2>Limited Liability</h2>
    <p>UNDER NO CIRCUMSTANCES SHALL <?= UtilityHelper::getCustomParameters('SiteName'); ?> OR ANY OF ITS EMPLOYEES, OWNERS, DIRECTORS, OFFICERS, AGENTS, VENDORS OR SUPPLIERS BE LIABLE FOR ANY DIRECT OR INDIRECT LOSSES OR DAMAGES ARISING OUT OF OR IN CONNECTION WITH THE USE OF OR INABILITY TO USE THIS WEBSITE.</p>
    <p>THIS IS A COMPREHENSIVE LIMITATION OF LIABILITY THAT APPLIES TO ALL LOSSES AND DAMAGES OF ANY KIND (WHETHER GENERAL, SPECIAL, CONSEQUENTIAL, INCIDENTAL, EXEMPLARY OR OTHERWISE, INCLUDING, WITHOUT LIMITATION, LOSS OF DATA, INCOME OR PROFITS), WHETHER IN CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, EVEN IF AN AUTHORIZED REPRESENTATIVE OF</p>
    <p>IF YOU ARE DISSATISFIED WITH THIS WEBSITE OR ANY CONTENT ON THE SITE, OR WITH THESE TERMS AND CONDITIONS, YOUR SOLE AND EXCLUSIVE REMEDY IS TO DISCONTINUE USING THIS WEBSITE. YOU ACKNOWLEDGE, BY YOUR USE OF THIS WEBSITE, THAT YOUR USE OF THE SITE IS AT YOUR SOLE RISK.</p>
    <p class="mb-5">APPLICABLE LAW MAY NOT ALLOW THE LIMITATION OF LIABILITY SET FORTH ABOVE, SO THIS LIMITATION OF LIABILITY MAY NOT APPLY TO YOU. IF ANY PART OF THIS LIMITATION ON LIABILITY IS FOUND TO BE INVALID OR UNENFORCEABLE FOR ANY REASON, THEN THE AGGREGATE LIABILITY OF <?= UtilityHelper::getCustomParameters('SiteName'); ?> UNDER SUCH CIRCUMSTANCES FOR LIABILITIES THAT OTHERWISE WOULD HAVE BEEN LIMITED SHALL NOT EXCEED ONE HUNDRED DOLLARS ($100.00).</p>

    <h2>Enforcement of Terms and Conditions Security</h2>
    <p class="mb-5">BY ACCESSING AND USING THIS WEBSITE, YOU AGREE THAT YOUR ACCESS TO AND USE OF THIS WEBSITE ARE SUBJECT TO THESE TERMS AND CONDITIONS, AS WELL AS ALL APPLICABLE LAWS, AS GOVERNED AND INTERPRETED PURSUANT TO THE LAWS OF THE STATE OF NEW YORK, UNITED STATES OF AMERICA.</p>

    <h2>Disputes</h2>
    <p class="mb-5"><?= UtilityHelper::getCustomParameters('SiteName'); ?> is committed to resolving all disputes in a fair, effective, and cost-efficient manner. We seek to resolve any customer concerns through our Customer Support services at <?= UtilityHelper::getCustomParameters('SiteEmail'); ?> If you are dissatisfied with our Customer Support service’s resolution of your matter, however, these Terms and Conditions provide that any dispute, controversy, or claim relating in any way to your use of any <?= UtilityHelper::getCustomParameters('SiteName'); ?> service, or to any products or services sold or distributed by <?= UtilityHelper::getCustomParameters('SiteName'); ?> through <?= UtilityHelper::getCustomParameters('SiteUrl'); ?> will be resolved by legal process in the State of New York.</p>

    <h2>Business Transitions</h2>
    <p class="mb-5">In the event that <?= UtilityHelper::getCustomParameters('SiteName'); ?> or its parent companies are sold or acquired by an outside organization, personal information may go along with the asset transfer. If this occurs, we may notify you 30 days prior to the official transfer date so you may move, delete, or change any information that you would like to if you choose to do so.</p>

    <h2>Contact Us</h2>
    <p>If you have any questions or concerns regarding these Terms and Conditions, this website, the privacy policy, or any products offered, please contact us through email.</p>
    <p class="mb-0">Contact <?= UtilityHelper::getCustomParameters('SiteName'); ?></p>
    <p class="mb-0">Email us at: <a href="mailto:<?= UtilityHelper::getCustomParameters('SiteEmail'); ?>"><?= UtilityHelper::getCustomParameters('SiteEmail'); ?></a></p>
  </div>
</section>